### ISSUE TITLE
connection issue with Dungeon / Fastgen both

### ISSUE THREAD

**Issue by Mohsyn** [cubiq/Comfy_Dungeon#5]
I was able to successfully install dungeon (and also fastgen)
but both of them work fine until it comes to connecting with comfyui:

that is where i get this error:

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
got prompt
Failed to validate prompt for output 13:
* CheckpointLoaderSimple 1:
  - Value not in list: ckpt_name: '' not in (list of length 38)
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

The error is same for fastgen and dungeon (so i am guessing it is something to do with way we connect with comfyui)
Kindly help

**Comment by davebrong** [comment]
It sounds like your model checkpoints haven't been downloaded, or placed in the proper folder.  Refer to the installation instructions.  The first two need to be placed into ComfyUI\models\checkpoints then the LORA has special instructions, make sure you read that carefully for the proper filename.

**Comment by Akrog** [comment]
I was also getting the same error when trying the cinematic preset:

```
Failed to validate prompt for output 13:
* CheckpointLoaderSimple 1:
  - Value not in list: ckpt_name: '' not in (list of length 22)
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

But it's just as @davebrong said, a problem with the checkpoint not being there. 
To be more precise, in my case the checkpoint file was `dreamshaperXL_v21TurboDPMSDE.safetensors` but the code looks for `DreamShaperXL_Turbo_v2_1.safetensors`.
I just created a symlink, restarted ComfyUI and I was good to go: `ln -s dreamshaperXL_v21TurboDPMSDE.safetensors DreamShaperXL_Turbo_v2_1.safetensors`.

**Comment by Mohsyn** [comment]
I modified the code to point to correct checkpoint and the issue was resolved. Thanks everyone for helping me out!
